# GENERATED by tools/generate.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  gemara-v1.schema.json

from __future__ import annotations

from gemara.v1._document import GemaraDocumentModel

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Model(RootModel[Any]):
    root: Any


class ArtifactMapping(BaseModel):
    """ArtifactMapping represents a mapping to an external artifact or artifact entry"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    reference_id: Annotated[str, Field(alias="reference-id")]
    """reference-id identifies an element from a MappingReference in the artifact's metadata"""
    remarks: str | None = None
    """remarks is prose regarding the mapped artifact or the mapping relationship"""


class ArtifactType(Enum):
    """
    ArtifactType identifies the kind of Gemara artifact for unambiguous parsing
    """

    capability_catalog = "CapabilityCatalog"
    control_catalog = "ControlCatalog"
    guidance_catalog = "GuidanceCatalog"
    threat_catalog = "ThreatCatalog"
    risk_catalog = "RiskCatalog"
    policy = "Policy"
    mapping_document = "MappingDocument"
    lexicon = "Lexicon"
    evaluation_log = "EvaluationLog"
    enforcement_log = "EnforcementLog"
    vector_catalog = "VectorCatalog"
    principle_catalog = "PrincipleCatalog"
    audit_log = "AuditLog"


class Capability(BaseModel):
    """Capability describes a system capability such as a feature, component or object."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    """description provides a detailed overview of this capability"""
    group: str
    """group references by id a catalog group that this capability belongs to"""
    id: str
    """id allows this entry to be referenced by other elements"""
    title: str
    """title describes this capability at a glance"""


class ConfidenceLevel(Enum):
    """
    ConfidenceLevel indicates the evaluator's confidence level in an assessment result.
    """

    undetermined = "Undetermined"
    low = "Low"
    medium = "Medium"
    high = "High"


class Constraint(BaseModel):
    """Constraint defines a prescriptive requirement that applies to a specific guidance or control."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """Unique ID for this constraint to enable Layer 5/6 tracking"""
    target_id: Annotated[str, Field(alias="target-id")]
    """Links to the specific Guidance or Control being constrained"""
    text: str
    """The prescriptive requirement/constraint text"""


class Dimensions(BaseModel):
    """Dimensions specify the applicability criteria for a policy"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    geopolitical: Annotated[list[str] | None, Field(min_length=1)] = None
    """geopolitical is an optional list of geopolitical regions"""
    groups: Annotated[list[str] | None, Field(min_length=1)] = None
    sensitivity: Annotated[list[str] | None, Field(min_length=1)] = None
    """sensitivity is an optional list of data classification levels"""
    technologies: Annotated[list[str] | None, Field(min_length=1)] = None
    """technologies is an optional list of technology categories or services"""
    users: Annotated[list[str] | None, Field(min_length=1)] = None
    """users is an optional list of user roles"""


class Disposition(Enum):
    """
    Disposition enumerates the possible enforcement outcomes.
    """

    undetermined = "Undetermined"
    enforced = "Enforced"
    tolerated = "Tolerated"
    clear = "Clear"


class EnforcementMethodType(Enum):
    gate = "Gate"
    remediation = "Remediation"


class EntityType(Enum):
    """
    EntityType specifies what entity is interacting in the workflow
    """

    human = "Human"
    software = "Software"
    software_assisted = "Software Assisted"


class EntryMapping(BaseModel):
    """EntryMapping represents how a specific entry maps to a MappingReference."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    entry_id: Annotated[str, Field(alias="entry-id")]
    """entry-id is the identifier being mapped to in the referenced artifact"""
    reference_id: Annotated[str, Field(alias="reference-id")]
    """reference-id is the id for a MappingReference entry in the artifact's metadata"""
    remarks: str | None = None
    """remarks is prose describing the mapping relationship"""


class EntryType(Enum):
    """
    EntryType enumerates the atomic units within Gemara artifacts that can participate in mappings
    """

    guideline = "Guideline"
    statement = "Statement"
    control = "Control"
    assessment_requirement = "AssessmentRequirement"
    capability = "Capability"
    threat = "Threat"
    risk = "Risk"
    vector = "Vector"
    principle = "Principle"


class EvaluationMethodType(Enum):
    intent = "Intent"
    behavioral = "Behavioral"


class EvidenceMapping(BaseModel):
    """
    EvidenceMapping identifies the source from which evidence was collected.
    reference-id names the MappingReference; coordinate or entry-id gives
    specificity within it; digest pins the observed content at collection time.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    coordinate: str | None = None
    """
    coordinate is the precise location within the stream identified by reference-id
    (e.g. an API path, file path, or JSON path expression).
    Do not set if entry-id is set.
    """
    digest: Annotated[str | None, Field(pattern="^[a-z0-9]+(?:[+._-][a-z0-9]+)*:[a-zA-Z0-9=_-]+$")] = None
    """digest is a cryptographic hash of the observed content at collection time; format: algorithm:encoded (e.g. sha256:abc123...)"""
    entry_id: Annotated[str | None, Field(alias="entry-id")] = None
    """
    entry-id identifies a specific entry within a referenced Gemara artifact.
    Do not set if coordinate is set.
    """
    reference_id: Annotated[str, Field(alias="reference-id")]
    """reference-id ties this evidence to a mapping-reference in the artifact's metadata"""
    remarks: str | None = None
    """remarks is prose regarding this evidence reference"""


class Group(BaseModel):
    """Group represents a classification or grouping that can be used in different contexts with semantic meaning derived from its usage"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    """description explains the significance and traits of entries to this group"""
    id: str
    """id allows this entry to be referenced by other elements"""
    title: str
    """title describes the purpose of this group at a glance"""


class GuidanceImport(BaseModel):
    """GuidanceImport defines how to import guidance documents with optional exclusions and constraints."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    constraints: Annotated[list[Constraint] | None, Field(min_length=1)] = None
    """Constraints allow policy authors to define ad hoc minimum requirements (e.g., "review at least annually")."""
    exclusions: Annotated[list[str] | None, Field(min_length=1)] = None
    reference_id: Annotated[str, Field(alias="reference-id")]


class GuidanceType(Enum):
    """
    GuidanceType restricts the possible types that a catalog may be listed as
    """

    standard = "Standard"
    regulation = "Regulation"
    best_practice = "Best Practice"
    framework = "Framework"


class ImplementationDetails(BaseModel):
    """ImplementationDetails specifies the timeline for policy implementation."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    end: AwareDatetime | None = None
    """Datetime represents an ISO 8601 formatted datetime string"""
    notes: str
    start: AwareDatetime
    """Datetime represents an ISO 8601 formatted datetime string"""


class ImplementationPlan(BaseModel):
    """ImplementationPlan defines when and how the policy becomes active."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    enforcement_timeline: Annotated[ImplementationDetails, Field(alias="enforcement-timeline")]
    evaluation_timeline: Annotated[ImplementationDetails, Field(alias="evaluation-timeline")]
    notification_process: Annotated[str | None, Field(alias="notification-process")] = None


class LexiconReference(BaseModel):
    """LexiconReference cites a source supporting a lexicon definition"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    citation: str
    """citation identifies the source material in prose"""
    url: Annotated[str | None, Field(pattern="^(https?|file)://[^\\s]+$")] = None
    """url points to supporting material when available"""


class LexiconTerm(BaseModel):
    """LexiconTerm is a single definition within a lexicon"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    definition: str
    """definition explains the meaning of the term"""
    id: str
    """id allows this entry to be referenced for anchors and tooling"""
    references: Annotated[list[LexiconReference] | None, Field(min_length=1)] = None
    """references cites external authorities supporting the definition"""
    synonyms: Annotated[list[str] | None, Field(min_length=1)] = None
    """synonyms lists alternative labels that should resolve to this term for linking"""
    title: str
    """title is the canonical name of the defined concept"""


class Lifecycle(Enum):
    """
    Lifecycle represents the lifecycle state of a guideline, control, or assessment requirement
    """

    active = "Active"
    draft = "Draft"
    deprecated = "Deprecated"
    retired = "Retired"


class MappingReference(BaseModel):
    """MappingReference represents a reference to an external document with full metadata."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """description is prose regarding the artifact's purpose or content"""
    id: str
    """
    id identifies this mapping reference within the artifact and, when url
    is absent, the referenced artifact's metadata.id.
    """
    title: str
    """title describes the purpose of this mapping reference at a glance"""
    url: Annotated[str | None, Field(pattern="^(https?|file)://[^\\s]+$")] = None
    """url is the path where the artifact may be retrieved; preferably responds with Gemara-compatible YAML/JSON"""
    version: str
    """version is the version identifier of the artifact being mapped to"""


class MappingTarget(BaseModel):
    """MappingTarget identifies a target entry with optional per-target metadata"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    applicability: Annotated[list[str] | None, Field(min_length=1)] = None
    """applicability constrains the contexts in which this target mapping holds"""
    confidence_level: Annotated[ConfidenceLevel | None, Field(alias="confidence-level")] = None
    entry_id: Annotated[str, Field(alias="entry-id")]
    """entry-id identifies the specific entry in the target artifact"""
    rationale: str | None = None
    """rationale explains why this relationship exists for this target"""
    remarks: str | None = None
    """remarks is general prose regarding this target mapping"""
    strength: float | None = None
    """strength is the author's estimate of how completely the source satisfies this target; range 1-10"""


class MethodType(Enum):
    behavioral = "Behavioral"
    intent = "Intent"
    remediation = "Remediation"
    gate = "Gate"


class MitigatedRisk(BaseModel):
    """MitigatedRisk represents a risk addressed by the policy"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """id allows this mitigated risk entry to be referenced by accepted risks"""
    risk: EntryMapping
    """risk references the risk being mitigated"""


class ModType(Enum):
    """
    ModType defines the type of modification to the assessment requirement.
    """

    add = "Add"
    modify = "Modify"
    remove = "Remove"
    replace_ = "Replace"
    override = "Override"


class ModeType(Enum):
    manual = "Manual"
    automated = "Automated"


class MultiEntryMapping(BaseModel):
    """MultiEntryMapping represents a mapping to an external reference with one or more entries."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    reference_id: Annotated[str, Field(alias="reference-id")]
    """reference-id identifies an element from a MappingReference in the artifact's metadata"""
    remarks: str | None = None
    """remarks is prose regarding the mapped artifact or the mapping relationship"""
    entries: Annotated[list[ArtifactMapping], Field(min_length=1)]
    """entries is a list of mapping entries"""


class Parameter(BaseModel):
    """Parameter defines a configurable parameter for assessment or enforcement activities."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    accepted_values: Annotated[list[str] | None, Field(alias="accepted-values", min_length=1)] = None
    description: str
    id: str
    label: str


class Principle(BaseModel):
    """Principle represents a foundational value or tenet that guides governance, design, and operational decisions"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    """description explains the principle and its expected outcomes"""
    group: str
    """group references by id a catalog group that this principle belongs to"""
    id: str
    """id allows this entry to be referenced by other elements"""
    rationale: str | None = None
    """rationale provides the context for this principle"""
    title: str
    """title describes the principle at a glance"""


class Rationale(BaseModel):
    """Rationale provides a structured way to communicate a guideline author's intent"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    goals: Annotated[list[str], Field(min_length=1)]
    """goals is a list of outcomes this guideline seeks to achieve"""
    importance: str
    """importance is an explanation of why this guideline matters"""


class Recommendation(BaseModel):
    """Recommendation provides a corrective action for an audit result"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    """id uniquely identifies this recommendation"""
    required: bool | None = None
    """required indicates whether this recommendation is a mandatory corrective action"""
    text: str
    """text describes the recommended corrective action"""


class RelationshipType(Enum):
    """
    RelationshipType enumerates the nature of the mapping between entries.
    """

    implements = "implements"
    implemented_by = "implemented-by"
    supports = "supports"
    supported_by = "supported-by"
    equivalent = "equivalent"
    subsumes = "subsumes"
    no_match = "no-match"
    relates_to = "relates-to"


class Result(Enum):
    not_run = "Not Run"
    passed = "Passed"
    failed = "Failed"
    needs_review = "Needs Review"
    not_applicable = "Not Applicable"
    unknown = "Unknown"


class ResultType(Enum):
    """
    ResultType classifies the nature of an audit result
    """

    gap = "Gap"
    finding = "Finding"
    observation = "Observation"
    strength = "Strength"


class RiskAppetite(Enum):
    """
    RiskAppetite defines the acceptable level of exposure for a risk category
    """

    minimal = "Minimal"
    low = "Low"
    moderate = "Moderate"
    high = "High"


class Scope(BaseModel):
    """Scope defines what is included and excluded from policy applicability."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    in_: Annotated[Dimensions | None, Field(alias="in")] = None
    out: Dimensions | None = None


class Severity(Enum):
    """
    Severity defines the assessed level of a risk based on its potential impact and likelihood
    """

    low = "Low"
    medium = "Medium"
    high = "High"
    critical = "Critical"


class Statement(BaseModel):
    """
    Statement represents a structural sub-requirement within a guideline;
    They do not increase strictness and all statements within a guideline apply together
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """id allows this entry to be referenced by other elements"""
    recommendations: Annotated[list[str] | None, Field(min_length=1)] = None
    """recommendations is a list of non-binding suggestions to aid in evaluation or enforcement of the statement"""
    text: str
    """text is the body of this statement"""
    title: str | None = None
    """title describes the contents of this statement"""


class TypedMapping(BaseModel):
    """TypedMapping extends ArtifactMapping with a required entry-type for all entries in this direction"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    reference_id: Annotated[str, Field(alias="reference-id")]
    """reference-id identifies an element from a MappingReference in the artifact's metadata"""
    remarks: str | None = None
    """remarks is prose regarding the mapped artifact or the mapping relationship"""
    entry_type: Annotated[EntryType, Field(alias="entry-type")]
    """entry-type identifies the type of atomic unit entries in this direction"""


class Vector(BaseModel):
    """A Vector represents a method, pathway, or technique through which a threat may be realized or an attack may be carried out."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    applicability: Annotated[list[str] | None, Field(min_length=1)] = None
    """applicability specifies the contexts in which this vector can manifest"""
    description: str
    """description explains how the attack vector works"""
    group: str
    """group references by id a catalog group that this vector belongs to"""
    id: str
    """id allows this vector to be referenced by other elements"""
    title: str
    """title describes the vector"""


class ReferenceId(RootModel[str]):
    root: str
    """reference-id is the id for a MappingReference entry in the artifact's metadata"""


class Type(Enum):
    """
    type identifies the kind of Gemara artifact for unambiguous parsing
    """

    capability_catalog = "CapabilityCatalog"
    control_catalog = "ControlCatalog"
    guidance_catalog = "GuidanceCatalog"
    threat_catalog = "ThreatCatalog"
    risk_catalog = "RiskCatalog"
    policy = "Policy"
    mapping_document = "MappingDocument"
    lexicon = "Lexicon"
    evaluation_log = "EvaluationLog"
    enforcement_log = "EnforcementLog"
    vector_catalog = "VectorCatalog"
    principle_catalog = "PrincipleCatalog"
    audit_log = "AuditLog"


class AcceptedRisk(BaseModel):
    """
    AcceptedRisk documents a risk the organization has chosen to accept,
    optionally linking it to a mitigated risk when the acceptance covers
    residual risk after partial mitigation.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """id allows this accepted risk entry to be referenced"""
    justification: str | None = None
    """justification explains why the risk is accepted"""
    risk: EntryMapping
    """risk references the risk being accepted"""
    scope: Scope | None = None
    """scope defines where the risk acceptance applies"""
    target_id: Annotated[str | None, Field(alias="target-id")] = None
    """target-id optionally links this acceptance to a mitigated risk entry"""


class AssessmentFinding(BaseModel):
    """AssessmentFinding maps an enforcement action to its originating assessment data across Layer 2, Layer 3, and Layer 5."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    log: EntryMapping
    """log maps to the EvaluationLog entry containing the finding"""
    plan: EntryMapping | None = None
    """plan maps to the Policy assessment plan that was executed"""
    requirement: EntryMapping | None = None
    """requirement maps to the Layer 2 assessment requirement that was evaluated"""
    result: Result
    """result is the assessment outcome that triggered the enforcement action"""


class AssessmentRequirement(BaseModel):
    """AssessmentRequirement describes a tightly scoped, verifiable condition that must be satisfied and confirmed by an evaluator"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    applicability: Annotated[list[str], Field(min_length=1)]
    """applicability is a list of strings describing the situations where this text functions as a requirement for its parent control"""
    id: str
    """id allows this entry to be referenced by other elements"""
    recommendation: str | None = None
    """recommendation provides readers with non-binding suggestions to aid in evaluation or enforcement of the requirement"""
    replaced_by: Annotated[EntryMapping | None, Field(alias="replaced-by")] = None
    """replaced-by references the assessment requirement that supersedes this one when deprecated or retired"""
    state: Lifecycle | None = None
    """state is the lifecycle state of this assessment requirement"""
    text: str
    """text is the body of the requirement, typically written as a MUST condition"""


class AssessmentRequirementModifier(BaseModel):
    """AssessmentRequirementModifier allows organizations to customize assessment requirements based on how an organization wants to gather evidence for the objective."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    applicability: Annotated[list[str] | None, Field(min_length=1)] = None
    """The updated applicability of the assessment requirement"""
    id: str
    modification_rationale: Annotated[str, Field(alias="modification-rationale")]
    modification_type: Annotated[ModType, Field(alias="modification-type")]
    recommendation: str | None = None
    """The updated recommendation for the assessment requirement"""
    target_id: Annotated[str, Field(alias="target-id")]
    text: str | None = None
    """The updated text of the assessment requirement"""


class CatalogImport(BaseModel):
    """CatalogImport defines how to import control catalogs with optional exclusions, constraints, and assessment requirement modifications."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    assessment_requirement_modifications: Annotated[
        list[AssessmentRequirementModifier] | None,
        Field(alias="assessment-requirement-modifications", min_length=1),
    ] = None
    constraints: Annotated[list[Constraint] | None, Field(min_length=1)] = None
    exclusions: Annotated[list[str] | None, Field(min_length=1)] = None
    reference_id: Annotated[str, Field(alias="reference-id")]


class Contact(BaseModel):
    """Contact is the contact information for a person or group"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    affiliation: str | None = None
    """affiliation is the organization with which the contact entity is associated, such as a team, school, or employer"""
    email: Annotated[str | None, Field(pattern="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")] = None
    """email is the preferred email address to reach the contact"""
    name: str
    """name is the preferred descriptor for the contact entity"""
    social: str | None = None
    """social is a social media handle or other profile for the contact, such as GitHub"""


class Control(BaseModel):
    """Control describes a safeguard or countermeasure with a clear objective and assessment requirements"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    assessment_requirements: Annotated[
        list[AssessmentRequirement],
        Field(alias="assessment-requirements", min_length=1),
    ]
    """assessment-requirements is a list of requirements that must be verified to confirm the control objective has been met"""
    group: str
    """group references by id a catalog group that this control belongs to"""
    guidelines: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    """guidelines documents relationships between this control and Layer 1 guideline artifacts"""
    id: str
    """id allows this entry to be referenced by other elements"""
    objective: str
    """objective is a unified statement of intent, which may encompass multiple situationally applicable requirements"""
    replaced_by: Annotated[EntryMapping | None, Field(alias="replaced-by")] = None
    """replaced-by references the control that supersedes this one when deprecated or retired"""
    state: Lifecycle | None = None
    """state is the lifecycle state of this control"""
    threats: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    """threats documents relationships between this control and Layer 2 threat artifacts"""
    title: str
    """title describes the purpose of this control at a glance"""


class ControlEvaluation(BaseModel):
    """ControlEvaluation contains the results of evaluating a single Layer 5 control."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    assessment_logs: Annotated[list[dict[str, Any]], Field(alias="assessment-logs")]
    """
    Enforce that control reference and the assessments' references match
    This formulation uses the control's reference if the assessment doesn't include a reference

    Require start timestamp on assessments that actually executed
    """
    control: EntryMapping
    message: str
    name: str
    result: Result


class Entity(BaseModel):
    """Entity represents a human or tool"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """description provides additional context about the entity"""
    id: str
    """id uniquely identifies the entity and allows this entry to be referenced by other elements"""
    name: str
    """name is the name of the entity"""
    type: EntityType
    """type specifies the type of entity interacting in the workflow"""
    uri: Annotated[str | None, Field(pattern="^https?://[^\\s]+$")] = None
    """uri is a general URI for the entity information"""
    version: str | None = None
    """version is the version of the entity (for tools; if applicable)"""


class Evidence(BaseModel):
    """
    Evidence records what was cited to support an opinion for a specific activity:
    raw data for the evaluation layer, evaluation and enforcement artifacts for the audit layer.
    At least one of payload or source MUST be present; an entry with neither is semantically incomplete.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    collected_at: Annotated[AwareDatetime, Field(alias="collected-at")]
    """collected-at is the timestamp when the evidence was gathered"""
    description: str | None = None
    """description explains what this evidence represents"""
    id: str
    """id uniquely identifies this evidence"""
    payload: Any | None = None
    """payload is the raw evidence data collected inline"""
    source: EvidenceMapping | None = None
    """source identifies the artifact or system from which this evidence was collected"""
    type: ArtifactType | str
    """type categorizes the kind of evidence"""


class Exemption(BaseModel):
    """Exemption describes a single scenario where the catalog is not applicable"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    """description identifies who or what is exempt from the full guidance"""
    reason: str
    """reason explains why the exemption is granted"""
    redirect: MultiEntryMapping | None = None
    """redirect points to alternative guidelines or controls that should be followed instead"""


class Guideline(BaseModel):
    """Guideline provides explanatory context and recommendations for designing optimal outcomes"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    applicability: Annotated[list[str] | None, Field(min_length=1)] = None
    """applicability specifies the contexts in which this guideline applies"""
    extends: EntryMapping | None = None
    """extends is an id for a guideline which this guideline adds to, in this document or elsewhere"""
    group: str
    """group provides an id to the group that this guideline belongs to"""
    id: str
    """id allows this entry to be referenced by other elements"""
    objective: str
    """objective is a unified statement of intent, which may encompass multiple situationally applicable statements"""
    principles: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    """principles documents the relationship between this guideline and one or more principles"""
    rationale: Rationale | None = None
    """rationale provides the context for this guideline"""
    recommendations: Annotated[list[str] | None, Field(min_length=1)] = None
    """recommendations is a list of non-binding suggestions to aid in evaluation or enforcement of the guideline"""
    replaced_by: Annotated[EntryMapping | None, Field(alias="replaced-by")] = None
    """replaced-by references the guideline that supersedes this one when deprecated or retired"""
    see_also: Annotated[list[str] | None, Field(alias="see-also", min_length=1)] = None
    """see-also lists related guideline IDs within the same GuidanceCatalog"""
    state: Lifecycle | None = None
    """state is the lifecycle state of this guideline"""
    statements: Annotated[list[Statement] | None, Field(min_length=1)] = None
    """statements is a list of structural sub-requirements within a guideline"""
    title: str
    """title describes the contents of this guideline"""
    vectors: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    """vector-mappings documents the relationship between this guideline and one or more vectors"""


class Imports(BaseModel):
    """Imports defines external policies, controls, and guidelines required by this policy."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    catalogs: Annotated[list[CatalogImport] | None, Field(min_length=1)] = None
    guidance: Annotated[list[GuidanceImport] | None, Field(min_length=1)] = None
    policies: Annotated[list[ArtifactMapping] | None, Field(min_length=1)] = None


class Justification(BaseModel):
    """Justification provides the assessment data and exception references that justify an enforcement action."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    assessments: Annotated[list[AssessmentFinding], Field(min_length=1)]
    """assessments links the action to one or more Assessment Findings"""
    exceptions: Annotated[list[ArtifactMapping] | None, Field(min_length=1)] = None
    """exceptions references approved Policy exceptions that authorize the action"""


class Mapping(BaseModel):
    """Mapping represents a relationship between a source entry and one or more target entries"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """id allows this mapping to be referenced by other elements"""
    relationship: RelationshipType
    """relationship describes the nature of the mapping between source and all targets"""
    remarks: str | None = None
    """remarks is general prose regarding this mapping"""
    source: str
    """source identifies the entry being mapped from by its entry-id"""
    targets: Annotated[list[MappingTarget] | None, Field(min_length=1)] = None
    """targets identifies the entries being mapped to; absent when relationship is no-match"""


class RACI(BaseModel):
    """RACI defines the roles responsible for managing an artifact"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    accountable: Annotated[list[Contact], Field(min_length=1)]
    """accountable identifies the entity ultimately accountable for the outcome"""
    consulted: Annotated[list[Contact] | None, Field(min_length=1)] = None
    """consulted identifies entities whose input is required when assessing or responding to the artifact"""
    informed: Annotated[list[Contact] | None, Field(min_length=1)] = None
    """informed identifies entities that should be notified about changes to the artifact status"""
    responsible: Annotated[list[Contact], Field(min_length=1)]
    """responsible identifies the entities responsible for executing work to manage or mitigate the artifact"""


class Resource(BaseModel):
    """Resource represents an entity that exists in the system and can be evaluated"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """description provides additional context about the entity"""
    id: str
    """id uniquely identifies the entity and allows this entry to be referenced by other elements"""
    name: str
    """name is the name of the entity"""
    type: EntityType
    """type specifies the type of entity interacting in the workflow"""
    uri: Annotated[str | None, Field(pattern="^https?://[^\\s]+$")] = None
    """uri is a general URI for the entity information"""
    version: str | None = None
    """version is the version of the entity (for tools; if applicable)"""
    environment: str | None = None
    """environment describes where the resource exists (e.g., production, staging, development, specific region)"""
    owner: Contact | None = None
    """owner is the contact information for the person or group responsible for managing or owning this resource"""


class Risk(BaseModel):
    """A Risk represents the potential for negative impact resulting from one or more threats."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    """description explains the risk scenario"""
    group: str
    """group references by id a catalog group that this risk belongs to"""
    id: str
    """id allows this risk to be referenced by other elements"""
    impact: str | None = None
    """impact describes the business or operational impact"""
    owner: RACI | None = None
    """owner defines the RACI roles responsible for managing this risk"""
    rank: int | None = None
    """
    rank optionally orders risks for the same catalog (e.g. when several share the same severity).
    Lower values mean higher relative importance. Omitted when the four severity levels are enough.
    When set, each value must be unique among all risks in the catalog that specify rank.
    """
    severity: Severity
    """severity describes the assessed level of this risk"""
    threats: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    """threats link this risk to Layer 2 threats"""
    title: str
    """title describes the risk"""


class RiskCategory(BaseModel):
    """RiskCategory describes a grouping of risks and defines appetite boundaries"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    """description explains the significance and traits of entries to this group"""
    id: str
    """id allows this entry to be referenced by other elements"""
    title: str
    """title describes the purpose of this group at a glance"""
    appetite: RiskAppetite
    """appetite defines the acceptable level of risk for this category"""
    max_severity: Annotated[Severity | None, Field(alias="max-severity")] = None
    """
    max-severity defines the risk tolerance boundary: the highest severity
    the organization will accept within this category
    """


class Risks(BaseModel):
    """Risks defines mitigated and accepted risks addressed by this policy."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    accepted: Annotated[list[AcceptedRisk] | None, Field(min_length=1)] = None
    """Accepted risks require rationale (justification) and may include scope. Controls addressing these risks are implicitly identified through threat mappings."""
    mitigated: Annotated[list[MitigatedRisk] | None, Field(min_length=1)] = None
    """Mitigated risks only need reference-id and risk-id (no justification required)"""


class ActionResult(BaseModel):
    """ActionResult captures a performed enforcement action."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    disposition: Disposition
    """disposition is the enforcement action taken"""
    end: AwareDatetime | None = None
    """end is the timestamp when the enforcement action concluded"""
    justification: Justification
    """justification links the action to its assessment findings and any applicable exceptions"""
    message: str | None = None
    """message provides additional context about the action"""
    method: EntryMapping
    """method references the specific AcceptedMethod entry within the Policy being enforced"""
    start: AwareDatetime
    """start is the timestamp when the enforcement action began"""
    steps: Annotated[list[str], Field(min_length=1)]
    """steps references the code paths or addresses that carried out this enforcement action"""


class Actor(BaseModel):
    """Actor represents an entity (human or tool) that performs actions in evaluations"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """description provides additional context about the entity"""
    id: str
    """id uniquely identifies the entity and allows this entry to be referenced by other elements"""
    name: str
    """name is the name of the entity"""
    type: EntityType
    """type specifies the type of entity interacting in the workflow"""
    uri: Annotated[str | None, Field(pattern="^https?://[^\\s]+$")] = None
    """uri is a general URI for the entity information"""
    version: str | None = None
    """version is the version of the entity (for tools; if applicable)"""
    contact: Contact | None = None
    """contact is contact information for the actor"""


class EnforcementMethod(BaseModel):
    """AcceptedMethod defines a method for evaluation or enforcement."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    executor: Actor | None = None
    id: str
    mode: ModeType
    required: bool | None = None
    type: EnforcementMethodType


class EvaluationMethod(BaseModel):
    """AcceptedMethod defines a method for evaluation or enforcement."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    executor: Actor | None = None
    id: str
    mode: ModeType
    required: bool | None = None
    type: EvaluationMethodType


class AssessmentLog(BaseModel):
    """AssessmentLog contains the results of executing a single assessment procedure for a control requirement."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    applicability: Annotated[list[str], Field(min_length=1)]
    """Applicability is elevated from the Layer 2 Assessment Requirement to aid in execution and reporting."""
    confidence_level: Annotated[ConfidenceLevel | None, Field(alias="confidence-level")] = None
    """ConfidenceLevel indicates the evaluator's confidence level in this specific assessment result."""
    description: str
    """Description provides a summary of the assessment procedure."""
    end: AwareDatetime | None = None
    """End is the timestamp when the assessment concluded."""
    evidence: Annotated[list[Evidence] | None, Field(min_length=1)] = None
    """Evidence records the raw data cited to support this assessment's opinion."""
    message: str
    """Message provides additional context about the assessment result."""
    plan: EntryMapping | None = None
    """Plan maps to the policy assessment plan being executed."""
    recommendation: str | None = None
    """Recommendation provides guidance on how to address a failed assessment."""
    requirement: EntryMapping
    """Requirement should map to the assessment requirement for this assessment."""
    result: Result
    """Result is the overall outcome of the assessment procedure, matching the result of the last step that was run."""
    start: AwareDatetime | None = None
    """
    Start is the timestamp when the assessment began.
    Assessments that never executed have no start time to record.
    """
    steps: Annotated[list[str], Field(min_length=1)]
    """Steps are sequential actions taken as part of the assessment, which may halt the assessment if a failure occurs."""
    steps_executed: Annotated[int | None, Field(alias="steps-executed")] = None
    """Steps-executed is the number of steps that were executed as part of the assessment."""


class AssessmentPlan(BaseModel):
    """AssessmentPlan defines how a specific assessment requirement is evaluated."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    evaluation_methods: Annotated[list[EvaluationMethod], Field(alias="evaluation-methods", min_length=1)]
    evidence_requirements: Annotated[str | None, Field(alias="evidence-requirements")] = None
    frequency: str
    id: str
    parameters: Annotated[list[Parameter] | None, Field(min_length=1)] = None
    requirement_id: Annotated[str, Field(alias="requirement-id")]


class AuditResult(BaseModel):
    """AuditResult records a single result with supporting evidence and recommendations."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    criteria_reference: Annotated[MultiEntryMapping, Field(alias="criteria-reference")]
    """criteria-reference maps this result to specific criteria entries"""
    description: str
    """description explains the result in detail"""
    evidence: Annotated[list[Evidence] | None, Field(min_length=1)] = None
    """evidence records the data sources that support this result"""
    id: str
    """id uniquely identifies this result"""
    recommendations: Annotated[list[Recommendation] | None, Field(min_length=1)] = None
    """recommendations records corrective actions for this result"""
    title: str
    """title describes this result at a glance"""
    type: ResultType
    """type classifies the nature of this result"""


class Metadata(BaseModel):
    """Metadata represents common metadata fields shared across all layers"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    applicability_groups: Annotated[list[Group] | None, Field(alias="applicability-groups", min_length=1)] = None
    """applicability-groups is a list of groups used to classify within this artifact to specify scope"""
    author: Actor
    """author is the person or group primarily responsible for this artifact"""
    date: AwareDatetime | None = None
    """date is the publication or effective date of this artifact"""
    description: str
    """description provides a high-level summary of the artifact's purpose and scope"""
    draft: bool | None = None
    """draft indicates whether this artifact is a pre-release version; open to modification"""
    gemara_version: Annotated[str, Field(alias="gemara-version")]
    """gemara-version declares which version of the Gemara specification this artifact conforms to"""
    id: str
    """id allows this entry to be referenced by other elements"""
    lexicon: ArtifactMapping | None = None
    """lexicon is a URI pointing to a controlled vocabulary or glossary relevant to this artifact"""
    mapping_references: Annotated[list[MappingReference] | None, Field(alias="mapping-references", min_length=1)] = None
    """mapping-references is a list of external documents referenced within this artifact"""
    type: ArtifactType
    """type identifies the kind of Gemara artifact for unambiguous parsing"""
    version: str | None = None
    """version is the version identifier of this artifact"""


class Threat(BaseModel):
    """Threat describes a specifically-scoped opportunity for a negative impact to the organization"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    actors: Annotated[list[Actor] | None, Field(min_length=1)] = None
    """actors describes the relevant internal or external threat actors"""
    capabilities: Annotated[list[MultiEntryMapping], Field(min_length=1)]
    """capabilities documents the relationship between this threat and a system capability"""
    description: str
    """description provides a detailed explanation of an opportunity for negative impact"""
    group: str
    """group references by id a catalog group that this threat belongs to"""
    id: str
    """id allows this entry to be referenced by other elements"""
    title: str
    """title describes this threat at a glance"""
    vectors: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    """vectors documents the relationship between this threat and one or more vectors"""


class AuditLogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["AuditLog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class CapabilityCatalogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["CapabilityCatalog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class ControlCatalogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["ControlCatalog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class EnforcementLogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["EnforcementLog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class EvaluationLogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["EvaluationLog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class GuidanceCatalogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["GuidanceCatalog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class LexiconMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["Lexicon"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class MappingDocumentMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    mapping_references: Annotated[list[MappingReference], Field(alias="mapping-references", min_length=1)]
    """mapping-references is a list of external documents referenced within this artifact"""
    type: Literal["MappingDocument"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class PolicyMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["Policy"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class PrincipleCatalogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["PrincipleCatalog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class RiskCatalogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["RiskCatalog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class ThreatCatalogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["ThreatCatalog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class VectorCatalogMetadata(Metadata):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["VectorCatalog"]
    """type identifies the kind of Gemara artifact for unambiguous parsing"""


class Catalog(GemaraDocumentModel):
    """Catalog describes a set of topically-associated entries"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    extends: list[ArtifactMapping] | None = None
    """extends references catalogs that this catalog builds upon"""
    groups: Annotated[list[Group] | None, Field(min_length=1)] = None
    """groups contains a list of groups that can be referenced by entries in this catalog"""
    imports: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    metadata: Metadata
    """metadata provides detailed data about this catalog"""
    title: str
    """title describes the purpose of this catalog at a glance"""


class Log(GemaraDocumentModel):
    """Log describes a set of recorded entries from a measurement activity"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    metadata: Metadata
    """metadata provides detailed data about this log"""
    target: Resource
    """target identifies the resource being evaluated"""


class AcceptedMethod(BaseModel):
    """AcceptedMethod defines a method for evaluation or enforcement."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    executor: Actor | None = None
    id: str
    mode: ModeType
    required: bool | None = None
    type: MethodType


class Adherence(BaseModel):
    """Adherence defines evaluation methods, assessment plans, enforcement methods, and non-compliance notifications."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    assessment_plans: Annotated[list[AssessmentPlan] | None, Field(alias="assessment-plans", min_length=1)] = None
    enforcement_methods: Annotated[list[EnforcementMethod] | None, Field(alias="enforcement-methods", min_length=1)] = (
        None
    )
    evaluation_methods: Annotated[list[EvaluationMethod] | None, Field(alias="evaluation-methods", min_length=1)] = None
    non_compliance: Annotated[str | None, Field(alias="non-compliance")] = None


class AuditLog(Log):
    """AuditLog records results from an audit performed against a target resource"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    metadata: AuditLogMetadata
    """metadata provides detailed data about this log"""
    target: Resource
    """target identifies the resource being evaluated"""
    criteria: Annotated[list[ArtifactMapping], Field(min_length=1)]
    """criteria defines the acceptable state for the audited resource"""
    owner: RACI | None = None
    """owner defines the RACI roles responsible for managing the audit"""
    results: Annotated[list[AuditResult], Field(min_length=1)]
    """results records audit results against the criteria"""
    summary: str
    """summary provides the high-level conclusion"""


class CapabilityCatalog(Catalog):
    """CapabilityCatalog describes a collection of system capabilities"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    extends: list[ArtifactMapping] | None = None
    """extends references catalogs that this catalog builds upon"""
    groups: Annotated[list[Group] | None, Field(min_length=1)] = None
    """groups contains a list of groups that can be referenced by entries in this catalog"""
    imports: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    metadata: CapabilityCatalogMetadata
    """metadata provides detailed data about this catalog"""
    title: str
    """title describes the purpose of this catalog at a glance"""
    capabilities: Annotated[list[Capability] | None, Field(min_length=1)] = None
    """capabilities is a list of capabilities defined by this catalog"""


class ControlCatalog(Catalog):
    """ControlCatalog describes a set of related controls and relevant metadata"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    extends: list[ArtifactMapping] | None = None
    """extends references catalogs that this catalog builds upon"""
    groups: Annotated[list[Group] | None, Field(min_length=1)] = None
    """groups contains a list of groups that can be referenced by entries in this catalog"""
    imports: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    metadata: ControlCatalogMetadata
    """metadata provides detailed data about this catalog"""
    title: str
    """title describes the purpose of this catalog at a glance"""
    controls: Annotated[list[Control] | None, Field(min_length=1)] = None
    """controls is a list of unique controls defined by this catalog"""


class EnforcementLog(Log):
    """EnforcementLog records actions taken in response to noncompliance findings from Layer 5 evaluations."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    metadata: EnforcementLogMetadata
    """metadata provides detailed data about this log"""
    target: Resource
    """target identifies the resource being evaluated"""
    actions: Annotated[list[ActionResult], Field(min_length=1)]
    """actions is the list of enforcement actions performed"""
    disposition: Disposition
    """disposition is the aggregate enforcement disposition across all actions in this log"""


class EvaluationLog(Log):
    """EvaluationLog contains the results of evaluating a set of Layer 2 controls."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    metadata: EvaluationLogMetadata
    """metadata provides detailed data about this log"""
    target: Resource
    """target identifies the resource being evaluated"""
    evaluations: Annotated[list[ControlEvaluation], Field(min_length=1)]
    result: Result
    """result is the aggregate outcome across all evaluations in this log"""


class GuidanceCatalog(Catalog):
    """GuidanceCatalog represents a concerted documentation effort to help bring about an optimal future without foreknowledge of the implementation details"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    extends: list[ArtifactMapping] | None = None
    """extends references catalogs that this catalog builds upon"""
    groups: Annotated[list[Group] | None, Field(min_length=1)] = None
    """groups contains a list of groups that can be referenced by entries in this catalog"""
    imports: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    metadata: GuidanceCatalogMetadata
    """metadata provides detailed data about this catalog"""
    title: str
    """title describes the purpose of this catalog at a glance"""
    exemptions: Annotated[list[Exemption] | None, Field(min_length=1)] = None
    """exemptions provides information about situations where this guidance is not applicable"""
    front_matter: Annotated[str | None, Field(alias="front-matter")] = None
    """front-matter provides introductory text for the document to be used during rendering"""
    guidelines: Annotated[list[Guideline] | None, Field(min_length=1)] = None
    """guidelines is a list of unique guidelines defined by this catalog"""
    type: GuidanceType
    """type categorizes this document based on the intent of its contents"""


class Lexicon(GemaraDocumentModel):
    """Lexicon is a controlled vocabulary or glossary artifact referenced by Metadata.lexicon"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    metadata: LexiconMetadata
    terms: Annotated[list[LexiconTerm], Field(min_length=1)]
    """terms is one or more defined entries for linking and rendering"""
    title: str
    """title describes the purpose of this lexicon at a glance"""


class MappingDocument(GemaraDocumentModel):
    """MappingDocument captures the user's intent for how entries in a source artifact relate to entries in a target artifact"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    mappings: Annotated[list[Mapping], Field(min_length=1)]
    """mappings is one or more atomic relationships between entries in the referenced artifacts"""
    metadata: MappingDocumentMetadata
    remarks: str | None = None
    """remarks is prose regarding this mapping document"""
    source_reference: Annotated[TypedMapping, Field(alias="source-reference")]
    """source-reference identifies the artifact being mapped from; must match a mapping-reference id"""
    target_reference: Annotated[TypedMapping, Field(alias="target-reference")]
    """target-reference identifies the artifact being mapped to; must match a mapping-reference id"""
    title: str
    """title describes the purpose of this mapping document at a glance"""


class Policy(GemaraDocumentModel):
    """Policy represents a policy document with metadata, contacts, scope, imports, implementation plan, risks, and adherence requirements."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    adherence: Adherence | None = None
    contacts: RACI
    implementation_plan: Annotated[ImplementationPlan | None, Field(alias="implementation-plan")] = None
    imports: Imports | None = None
    metadata: PolicyMetadata
    risks: Risks | None = None
    scope: Scope | None = None
    title: str


class PrincipleCatalog(Catalog):
    """PrincipleCatalog describes a set of related principles and relevant metadata"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    extends: list[ArtifactMapping] | None = None
    """extends references catalogs that this catalog builds upon"""
    groups: Annotated[list[Group] | None, Field(min_length=1)] = None
    """groups contains a list of groups that can be referenced by entries in this catalog"""
    imports: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    metadata: PrincipleCatalogMetadata
    """metadata provides detailed data about this catalog"""
    title: str
    """title describes the purpose of this catalog at a glance"""
    principles: Annotated[list[Principle] | None, Field(min_length=1)] = None
    """principles is a list of unique principles defined by this catalog"""


class RiskCatalog(Catalog):
    """
    A RiskCatalog is a structured collection of documented risks that may affect an organization,
    system, or service. It provides a centralized reference for risks that can be mapped to threats
    and referenced by policies when documenting how those risks are mitigated or accepted.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    extends: list[ArtifactMapping] | None = None
    """extends references catalogs that this catalog builds upon"""
    groups: Annotated[list[Group | RiskCategory] | None, Field(min_length=1)] = None
    """groups narrows the base groups to risk categories with appetite and severity boundaries"""
    imports: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    metadata: RiskCatalogMetadata
    """metadata provides detailed data about this catalog"""
    title: str
    """title describes the purpose of this catalog at a glance"""
    risks: Annotated[list[Risk] | None, Field(min_length=1)] = None
    """risks is a list of risks defined by this catalog"""


class ThreatCatalog(Catalog):
    """ThreatCatalog describes a set of topically-associated threats"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    extends: list[ArtifactMapping] | None = None
    """extends references catalogs that this catalog builds upon"""
    groups: Annotated[list[Group] | None, Field(min_length=1)] = None
    """groups contains a list of groups that can be referenced by entries in this catalog"""
    imports: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    metadata: ThreatCatalogMetadata
    """metadata provides detailed data about this catalog"""
    title: str
    """title describes the purpose of this catalog at a glance"""
    threats: Annotated[list[Threat] | None, Field(min_length=1)] = None
    """threats is a list of threats defined by this catalog"""


class VectorCatalog(Catalog):
    """Catalog describes a set of topically-associated entries"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    extends: list[ArtifactMapping] | None = None
    """extends references catalogs that this catalog builds upon"""
    groups: Annotated[list[Group] | None, Field(min_length=1)] = None
    """groups contains a list of groups that can be referenced by entries in this catalog"""
    imports: Annotated[list[MultiEntryMapping] | None, Field(min_length=1)] = None
    metadata: VectorCatalogMetadata
    """metadata provides detailed data about this catalog"""
    title: str
    """title describes the purpose of this catalog at a glance"""
    vectors: Annotated[list[Vector] | None, Field(min_length=1)] = None
    """vectors is a list of attack vectors documented in this catalog"""


__all__ = [
    "AcceptedMethod",
    "AcceptedRisk",
    "ActionResult",
    "Actor",
    "Adherence",
    "ArtifactMapping",
    "ArtifactType",
    "AssessmentFinding",
    "AssessmentLog",
    "AssessmentPlan",
    "AssessmentRequirement",
    "AssessmentRequirementModifier",
    "AuditLog",
    "AuditLogMetadata",
    "AuditResult",
    "Capability",
    "CapabilityCatalog",
    "CapabilityCatalogMetadata",
    "Catalog",
    "CatalogImport",
    "ConfidenceLevel",
    "Constraint",
    "Contact",
    "Control",
    "ControlCatalog",
    "ControlCatalogMetadata",
    "ControlEvaluation",
    "Dimensions",
    "Disposition",
    "EnforcementLog",
    "EnforcementLogMetadata",
    "EnforcementMethod",
    "EnforcementMethodType",
    "Entity",
    "EntityType",
    "EntryMapping",
    "EntryType",
    "EvaluationLog",
    "EvaluationLogMetadata",
    "EvaluationMethod",
    "EvaluationMethodType",
    "Evidence",
    "EvidenceMapping",
    "Exemption",
    "Group",
    "GuidanceCatalog",
    "GuidanceCatalogMetadata",
    "GuidanceImport",
    "GuidanceType",
    "Guideline",
    "ImplementationDetails",
    "ImplementationPlan",
    "Imports",
    "Justification",
    "Lexicon",
    "LexiconMetadata",
    "LexiconReference",
    "LexiconTerm",
    "Lifecycle",
    "Log",
    "Mapping",
    "MappingDocument",
    "MappingDocumentMetadata",
    "MappingReference",
    "MappingTarget",
    "Metadata",
    "MethodType",
    "MitigatedRisk",
    "ModType",
    "ModeType",
    "MultiEntryMapping",
    "Parameter",
    "Policy",
    "PolicyMetadata",
    "Principle",
    "PrincipleCatalog",
    "PrincipleCatalogMetadata",
    "RACI",
    "Rationale",
    "Recommendation",
    "ReferenceId",
    "RelationshipType",
    "Resource",
    "Result",
    "ResultType",
    "Risk",
    "RiskAppetite",
    "RiskCatalog",
    "RiskCatalogMetadata",
    "RiskCategory",
    "Risks",
    "Scope",
    "Severity",
    "Statement",
    "Threat",
    "ThreatCatalog",
    "ThreatCatalogMetadata",
    "TypedMapping",
    "Vector",
    "VectorCatalog",
    "VectorCatalogMetadata",
]
