# GENERATED by tools/generate.py. Do not edit.
"""Document-type registry derived from the schema's `metadata.type` discriminators."""

from __future__ import annotations

from typing import Final, TypeAlias

from pydantic import BaseModel

from gemara.v1 import _models

SCHEMA_VERSION: Final[str] = "1.5.0"
"""The Gemara schema version these models were generated from."""

DOCUMENT_TYPES: Final[dict[str, type[BaseModel]]] = {
    "AuditLog": _models.AuditLog,
    "CapabilityCatalog": _models.CapabilityCatalog,
    "ControlCatalog": _models.ControlCatalog,
    "EnforcementLog": _models.EnforcementLog,
    "EvaluationLog": _models.EvaluationLog,
    "GuidanceCatalog": _models.GuidanceCatalog,
    "Lexicon": _models.Lexicon,
    "MappingDocument": _models.MappingDocument,
    "Policy": _models.Policy,
    "PrincipleCatalog": _models.PrincipleCatalog,
    "RiskCatalog": _models.RiskCatalog,
    "ThreatCatalog": _models.ThreatCatalog,
    "VectorCatalog": _models.VectorCatalog,
}
"""Maps a document's `metadata.type` to its model. Never hand-maintain this."""

GemaraDocument: TypeAlias = (
    _models.AuditLog
    | _models.CapabilityCatalog
    | _models.ControlCatalog
    | _models.EnforcementLog
    | _models.EvaluationLog
    | _models.GuidanceCatalog
    | _models.Lexicon
    | _models.MappingDocument
    | _models.Policy
    | _models.PrincipleCatalog
    | _models.RiskCatalog
    | _models.ThreatCatalog
    | _models.VectorCatalog
)
"""Union of every document-type model. The return type of `load`/`loads`."""

__all__ = ["DOCUMENT_TYPES", "GemaraDocument", "SCHEMA_VERSION"]
