#!/usr/bin/env python3
"""Generate Pydantic v2 models and the document registry from the vendored schema.

Reads `schemas/gemara-v1.schema.json`, writes `src/gemara/v1/_models.py`
and `src/gemara/v1/_registry.py`.

Usage: python tools/generate.py
"""

from __future__ import annotations

import ast
import json
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Final

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = PROJECT_ROOT / "schemas" / "gemara-v1.schema.json"
PROVENANCE_PATH = PROJECT_ROOT / "schemas" / "provenance.json"
PACKAGE_DIR = PROJECT_ROOT / "src" / "gemara" / "v1"
MODELS_PATH = PACKAGE_DIR / "_models.py"
REGISTRY_PATH = PACKAGE_DIR / "_registry.py"

# Recorded in the generated header, so it must be stable across runs or the
# drift gate fails on the header alone.
CODEGEN_INPUT_NAME = "gemara-v1.schema.json"
# `Final` so mypy narrows this to its literal type: the API types `preset` as a
# Literal of valid names, so a typo is now a type error rather than a runtime one.
CODEGEN_PRESET: Final = "practical-py311-20260619"

GENERATED_MARKER = "# GENERATED by tools/generate.py. Do not edit."

# Generated names excluded from the public surface (`__all__`), each for its
# own reason -- none of these is something a consumer should reach via
# `from gemara.v1 import *`:
#   - `Model` is a bare `RootModel[Any]` datamodel-codegen emits for the
#     schema's own JSON Schema root; it carries no Gemara semantics.
#   - `Type` duplicates `ArtifactType` (same enum values, generated a second
#     time from an inline `type` property instead of a `$ref`), and its name
#     is exactly the kind of generic identifier `import *` should not export.
# `ReferenceId` is deliberately NOT here: it is a real schema type.
DENYLISTED_MODEL_NAMES = frozenset({"Model", "Type"})


class GenerateError(RuntimeError):
    """The schema could not be turned into models."""


def inject_metadata_titles(schema: dict[str, Any]) -> dict[str, str]:
    """Name each per-document metadata subschema and collect the discriminators.

    A document type is a definition whose `metadata` property narrows `type` to
    a `const`. Without a `title`, datamodel-codegen names these `Metadata1`…
    `MetadataN`. The old generator instead replaced them with a generic $ref,
    destroying the discriminator entirely -- that is defect 4, and it must never
    be reintroduced.
    """
    doc_types: dict[str, str] = {}
    for name, definition in schema["$defs"].items():
        if not isinstance(definition, dict):
            continue
        metadata = (definition.get("properties") or {}).get("metadata")
        if not isinstance(metadata, dict):
            continue
        type_schema = (metadata.get("properties") or {}).get("type")
        if not isinstance(type_schema, dict) or "const" not in type_schema:
            continue
        metadata["title"] = f"{name}Metadata"
        doc_types[str(type_schema["const"])] = name
    return doc_types


def check_document_types(schema: dict[str, Any], doc_types: dict[str, str]) -> None:
    """The discriminators must reproduce #ArtifactType exactly."""
    artifact_type = schema.get("$defs", {}).get("ArtifactType", {})
    declared = set(artifact_type.get("enum", []))
    if not declared:
        raise GenerateError("schema has no #ArtifactType enum")
    found = set(doc_types)
    if declared != found:
        missing = ", ".join(sorted(declared - found)) or "none"
        extra = ", ".join(sorted(found - declared)) or "none"
        raise GenerateError(f"document types disagree with #ArtifactType (missing: {missing}; unexpected: {extra})")


def fold_hidden_definitions(schema: dict[str, Any]) -> int:
    """Replace transparent CUE-internal definitions with their base definitions.

    Hidden CUE structs are exported as underscore-prefixed `$defs`. A transparent
    wrapper contains only a reference and descriptive metadata, so it can point
    directly to its base type instead of becoming a duplicate generated model.
    Generation fails for a non-transparent hidden definition rather than silently
    discarding a constraint it might carry.
    """
    definitions = schema.get("$defs")
    if not isinstance(definitions, dict):
        raise GenerateError("schema has no $defs")

    hidden_refs: dict[str, str] = {}
    for name, definition in definitions.items():
        if not isinstance(name, str) or not name.startswith("_"):
            continue
        if not isinstance(definition, dict):
            raise GenerateError(f"hidden definition {name!r} is not an object")
        unsupported = set(definition) - {"$ref", "description", "type"}
        ref = definition.get("$ref")
        if unsupported or not isinstance(ref, str) or not ref.startswith("#/$defs/"):
            raise GenerateError(f"hidden definition {name!r} cannot be safely folded")
        hidden_refs[name] = ref

    def resolve(ref: str, seen: set[str]) -> str:
        name = ref.removeprefix("#/$defs/")
        if name not in hidden_refs:
            return ref
        if name in seen:
            raise GenerateError(f"hidden definition reference cycle: {name!r}")
        return resolve(hidden_refs[name], seen | {name})

    replacements = {f"#/$defs/{name}": resolve(ref, {name}) for name, ref in hidden_refs.items()}

    def visit(node: Any) -> None:
        if isinstance(node, dict):
            if node.get("$ref") in replacements:
                node["$ref"] = replacements[node["$ref"]]
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(schema)
    for name in hidden_refs:
        del definitions[name]
    return len(replacements)


def ignore_unknown_properties(schema: dict[str, Any]) -> int:
    """Reopen every closed object so unknown properties are ignored, not rejected.

    CUE emits closed structs, which project to `additionalProperties: false` and
    generate `ConfigDict(extra="forbid")`. That makes forward compatibility
    impossible: Gemara v1 evolves additively, so the moment upstream adds an
    optional field, every already-released reader rejects every document using
    it -- until the reader re-syncs and ships. A schema library that rejects
    valid documents of its own major version is worse than no library.

    The key is removed rather than set to `true`. An unset `additionalProperties`
    emits no `extra` setting at all, and pydantic's default is "ignore": unknown
    properties are accepted, then dropped rather than carried onto the model.
    That is deliberate on two counts. It matches go-gemara, where a property with
    no corresponding struct field is neither stored nor re-marshalled, so the same
    document processed by either SDK yields the same output. And it keeps this
    package's models honest as a typed surface -- `extra="allow"` would attach
    attributes at runtime that appear in no stub and are invisible to every type
    checker, which is a poor trade in a distribution whose entire product is types.

    Strictness is not lost, only relocated: required fields, enums, patterns and
    length bounds still apply, and CUE remains the source of truth for the
    cross-field semantics no structural validator can express (see the README's
    known limitations). Measured against the vendored corpus, no `bad-*` fixture
    is detected via `extra="forbid"` -- every rejection comes from a missing
    field, an enum, a pattern, or a length bound.

    Only an explicit `false` is removed; a schema that constrains
    `additionalProperties` by type is left alone. Mutates `schema` in place.
    Returns the number of objects reopened, for logging.
    """
    reopened = 0

    def visit(node: Any) -> None:
        nonlocal reopened
        if isinstance(node, dict):
            if node.get("additionalProperties") is False:
                del node["additionalProperties"]
                reopened += 1
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(schema)
    return reopened


def recover_array_allof_element_type(schema: dict[str, Any]) -> int:
    """Collapse an array-typed `allOf` node into its one strongly-typed arm.

    CUE compiles a comprehension's array constraint (e.g. "Clear dispositions
    only contain Passed results") and its element-typed constraint into
    separate `allOf` arms that both narrow `type: array`. `datamodel-codegen`
    does not merge an `allOf` of arrays, so every arm collapses to `Any`,
    discarding the element type and any `minItems`/`items` constraint.

    This is only safe to undo when exactly one arm carries `items`: that arm
    is then the sole source of element shape. When two or more arms carry
    `items`, which one is authoritative is ambiguous -- they may even
    disagree, as with `ControlEvaluation.assessment-logs`, where CUE defaults
    a field in from elsewhere that a fixed element type cannot express -- so
    the node is left untouched rather than guessing.

    Known limitation: the losing arm(s) are discarded whole. Only the winning
    arm and the outer node's own sibling keys survive, so any keyword a losing
    arm carries is dropped silently. That is lossless against the schema this
    was written for -- Gemara v1.5.0's sole collapsing site,
    `EnforcementLog.actions`, has a losing arm holding just `description` and
    `type`, comprehension metadata that no structural validator can enforce
    anyway (`bad-enforcement-clear-failed`, written to test exactly that rule,
    parses here and in go-gemara alike). But it is an assumption about the
    shape of CUE's output, not a checked invariant: if a future upstream ref
    ever emits a losing arm carrying a real array constraint -- `maxItems`,
    `uniqueItems`, its own `minItems` -- that constraint vanishes, and the only
    signal is a field validating more loosely in the `_models.py` drift diff,
    which is an absence and easy to miss.

    Deliberately not guarded with an assertion. Failing generation over a
    keyword nobody has seen would block a future `sync-schema` on a schema
    change that is very likely irrelevant, and merging losing arms properly
    means implementing `allOf` intersection semantics per keyword -- the class
    of repair pass this project banned after the predecessor's
    `flatten_struct_embedding` got it wrong. If it ever bites, the fix is to
    merge the specific keyword rather than to generalise.

    Mutates `schema` in place (this pass runs on the in-memory dict before
    codegen; it never touches anything under `schemas/`). Returns the number
    of nodes collapsed, for logging.
    """
    collapsed = 0

    def visit(node: Any) -> None:
        nonlocal collapsed
        if isinstance(node, dict):
            all_of = node.get("allOf")
            if (
                isinstance(all_of, list)
                and all_of
                and all(isinstance(arm, dict) and arm.get("type") == "array" for arm in all_of)
            ):
                arms_with_items = [arm for arm in all_of if "items" in arm]
                if len(arms_with_items) == 1:
                    winner = arms_with_items[0]
                    merged = dict(winner)
                    for key, value in node.items():
                        if key != "allOf" and key not in merged:
                            merged[key] = value
                    node.clear()
                    node.update(merged)
                    collapsed += 1
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(schema)
    return collapsed


def public_model_names(source: str) -> list[str]:
    """Top-level class names in the generated module, in definition order."""
    tree = ast.parse(source)
    return [node.name for node in tree.body if isinstance(node, ast.ClassDef) and not node.name.startswith("_")]


def run_codegen(schema: dict[str, Any]) -> str:
    """Generate the models from the in-memory schema, in-process.

    `datamodel_code_generator.generate` takes the schema as a mapping and returns
    the source, so nothing is serialised to disk and the CLI need not be on PATH.
    `input_filename` sets the name the generated header records; it is fixed
    because the drift gate compares committed bytes, and a varying header would
    fail it on its own. Verified byte-identical to the equivalent CLI invocation.

    Imported here rather than at module scope so this module's pure functions --
    the ones the unit tests exercise -- stay importable without the codegen
    dependency installed. Only regenerating needs it.
    """
    from datamodel_code_generator import Error, InputFileType, generate

    with tempfile.TemporaryDirectory() as tmp:
        output = Path(tmp) / "models.py"
        try:
            generate(
                schema,
                input_file_type=InputFileType.JsonSchema,
                input_filename=CODEGEN_INPUT_NAME,
                schema_version="2020-12",
                preset=CODEGEN_PRESET,
                output=output,
            )
        except Error as exc:  # datamodel-code-generator's own error type
            raise GenerateError(f"codegen failed: {exc}") from exc
        return output.read_text(encoding="utf-8")


def render_models(body: str, model_names: list[str], document_models: list[str]) -> str:
    future_import = "from __future__ import annotations\n"
    if body.count(future_import) != 1:
        raise GenerateError("generated models have an unexpected future-import layout")
    body = body.replace(future_import, f"{future_import}\nfrom gemara.v1._document import GemaraDocumentModel\n", 1)
    for model in document_models:
        declaration = f"class {model}(BaseModel):"
        if body.count(declaration) != 1:
            raise GenerateError(f"generated models have an unexpected declaration for document model {model!r}")
        body = body.replace(declaration, f"class {model}(GemaraDocumentModel):")
    exports = "\n".join(f'    "{name}",' for name in sorted(model_names) if name not in DENYLISTED_MODEL_NAMES)
    return f"{GENERATED_MARKER}\n{body.rstrip()}\n\n\n__all__ = [\n{exports}\n]\n"


def render_registry(doc_types: dict[str, str], schema_version: str, model_names: list[str]) -> str:
    known = set(model_names)
    entries = []
    document_models = []
    for const in sorted(doc_types):
        model = doc_types[const]
        if model not in known:
            raise GenerateError(f"document type {const!r} maps to unknown model {model!r}")
        entries.append(f'    "{const}": _models.{model},')
        document_models.append(model)
    body = "\n".join(entries)
    union = " | ".join(f"_models.{model}" for model in document_models)
    return f'''{GENERATED_MARKER}
"""Document-type registry derived from the schema's `metadata.type` discriminators."""

from __future__ import annotations

from typing import Final, TypeAlias

from pydantic import BaseModel

from gemara.v1 import _models

SCHEMA_VERSION: Final[str] = "{schema_version}"
"""The Gemara schema version these models were generated from."""

DOCUMENT_TYPES: Final[dict[str, type[BaseModel]]] = {{
{body}
}}
"""Maps a document's `metadata.type` to its model. Never hand-maintain this."""

GemaraDocument: TypeAlias = {union}
"""Union of every document-type model. The return type of `load`/`loads`."""

__all__ = ["DOCUMENT_TYPES", "GemaraDocument", "SCHEMA_VERSION"]
'''


def ruff_format(*paths: Path) -> None:
    """Format the output so the drift gate compares formatted bytes to formatted bytes."""
    result = subprocess.run(
        ["ruff", "format", *(str(p) for p in paths)],
        capture_output=True,
        encoding="utf-8",
        check=False,
    )
    if result.returncode != 0:
        raise GenerateError(f"ruff format failed: {result.stderr.strip()}")


def main() -> int:
    if not SCHEMA_PATH.exists():
        raise GenerateError(f"{SCHEMA_PATH} is missing; run `poe sync-schema` first")

    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    provenance = json.loads(PROVENANCE_PATH.read_text(encoding="utf-8"))
    schema_version = str(provenance["ref"]).lstrip("v")

    print(f"Generating models for Gemara {schema_version} ({len(schema['$defs'])} $defs)")

    doc_types = inject_metadata_titles(schema)
    check_document_types(schema, doc_types)
    print(f"  {len(doc_types)} document types match #ArtifactType")

    folded = fold_hidden_definitions(schema)
    print(f"  Folded {folded} hidden definition(s)")

    recovered = recover_array_allof_element_type(schema)
    print(f"  Recovered element type for {recovered} array allOf site(s)")

    reopened = ignore_unknown_properties(schema)
    print(f"  Reopened {reopened} closed objects for forward compatibility")

    body = run_codegen(schema)
    model_names = public_model_names(body)
    print(f"  Generated {len(model_names)} models")

    PACKAGE_DIR.mkdir(parents=True, exist_ok=True)
    MODELS_PATH.write_text(render_models(body, model_names, sorted(doc_types.values())), encoding="utf-8")
    REGISTRY_PATH.write_text(render_registry(doc_types, schema_version, model_names), encoding="utf-8")
    ruff_format(MODELS_PATH, REGISTRY_PATH)

    print(f"  Wrote {MODELS_PATH.relative_to(PROJECT_ROOT)}")
    print(f"  Wrote {REGISTRY_PATH.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
